// Code generated by `umbral gen-client`. DO NOT EDIT.
//
// client.js — the runtime (ES module)
//
// Regenerate after any model or REST-resource change:
//     cargo run -- gen-client --out <this directory>
//
// Base path: /api. Auth: Bearer token / apiKey (X-API-Key) / session cookie.


/** Thrown when the API returns a non-2xx response. `body` is the parsed error. */
export class UmbralError extends Error {
  constructor(status, body) {
    super(`umbral: request failed with status ${status}`);
    this.name = "UmbralError";
    this.status = status;
    this.body = body;
  }
}

/** A list query. Built by `Umbral.from(table)`; see client.d.ts for the types. */
export class Query {
  constructor(client, table) {
    this.client = client;
    this.table = table;
    this.params = new URLSearchParams();
  }

  /** Field filters — keys and value types are specific to this model. */
  filter(f) {
    for (const [k, v] of Object.entries(f || {})) {
      if (v === undefined) continue;
      this.params.set(k, Array.isArray(v) ? v.join(",") : String(v));
    }
    return this;
  }

  /** Full-text `?search=` across the model's searchable columns. */
  search(term) { this.params.set("search", term); return this; }

  /** `?ordering=` — pass fields; prefix `-` for descending. */
  orderBy(...fields) { this.params.set("ordering", fields.join(",")); return this; }

  /** 1-based page number (`?page=`). */
  page(v) { this.params.set("page", String(v)); return this; }

  /** Rows per page (`?page_size=`). */
  pageSize(v) { this.params.set("page_size", String(v)); return this; }

  /** Set any raw query param — the escape hatch for params the typed builder
      methods don't cover (a custom paginator's cursor, a one-off flag). */
  param(key, value) { this.params.set(key, String(value)); return this; }

  /** Sparse fieldset (`?fields=`) — fetch only these columns. */
  fields(...cols) { this.params.set("fields", cols.join(",")); return this; }

  /** Fetch the list. Resolves to the envelope your paginator emits. */
  async list() {
    const qs = this.params.toString();
    const path = `/api/${this.table}/` + (qs ? `?${qs}` : "");
    return this.client._request("GET", path);
  }
}


/** The session client — `api.auth`. Wraps this app's auth endpoints and owns
    the bearer token, which every subsequent request picks up automatically. */
export class AuthClient {
  constructor(client) { this.client = client; }

  /** The bearer token currently in use, or null. */
  get token() { return this.client._token; }

  /** Sign in. Stores the returned token; later calls send it automatically.
      (Browsers also get the server's session cookie, so either works.) */
  async login(credentials) {
    const out = await this.client._request("POST", "/api/auth/login", credentials);
    this.client._setToken(out && out.token ? out.token : null);
    return out;
  }

  /** Register, then adopt the returned token (same shape as login). */
  async register(body) {
    const out = await this.client._request("POST", "/api/auth/register", body);
    if (out && out.token) this.client._setToken(out.token);
    return out;
  }

  /** Clear the server session, then drop the token locally — even if the
      request fails, so a user pressing "log out" is never left holding one. */
  async logout() {
    try { await this.client._request("POST", "/api/auth/logout"); }
    finally { this.client._setToken(null); }
  }

  /** The current user, or `null` when not signed in. A 401 is the ANSWER to
      "am I logged in?", not an error — so it resolves null instead of throwing.
      Any other failure still throws. */
  async me() {
    try {
      return await this.client._request("GET", "/api/auth/me");
    } catch (err) {
      if (err instanceof UmbralError && err.status === 401) return null;
      throw err;
    }
  }
}

/** A typed client for this app's REST API. `new Umbral("https://api.example.com")`. */
export class Umbral {
  constructor(baseUrl, opts = {}) {
    this.baseUrl = String(baseUrl).replace(/\/+$/, "");
    this.opts = opts;
    this.realtimePath = (opts.realtimePath ?? "/realtime").replace(/\/+$/, "");
    this._rt = null;
    // The live bearer token: seeded from `opts.token` and replaced whenever it
    // changes. Every request reads it from here.
    this._token = opts.token ?? null;
    this.auth = new AuthClient(this);
  }

  /** @internal Set the live token and notify the app so it can persist it.
   *  Deliberately NOT written to localStorage by the client: that is readable by
   *  any XSS on the page. Browsers already get an httpOnly session cookie; if you
   *  need the token across reloads, persist it yourself via `onToken` and decide
   *  the trade-off knowingly. */
  _setToken(token) {
    this._token = token;
    if (this.opts.onToken) this.opts.onToken(token);
  }

  /** Start a query against a REST-exposed table. */
  from(table) { return new Query(this, table); }

  /** Retrieve one row by primary key. */
  get(table, id) { return this._request("GET", `/api/${table}/${id}`); }

  /** Create a row. */
  create(table, data) { return this._request("POST", `/api/${table}/`, data); }

  /** Partially update a row (PATCH). */
  update(table, id, data) { return this._request("PATCH", `/api/${table}/${id}`, data); }

  /** Delete a row by primary key. */
  async delete(table, id) { await this._request("DELETE", `/api/${table}/${id}`); }

  /** Subscribe to `created` / `updated` / `deleted` for a model.
   *
   *  Delegates to the realtime plugin's runtime (loaded once from
   *  `{realtimePath}/client.js`) rather than opening its own EventSource — so
   *  every subscription in every tab shares ONE server connection via
   *  SharedWorker, with presence and graceful degradation. Opening an
   *  EventSource per subscription would blow the browser's per-origin
   *  connection cap at ~6 models.
   *
   *  Returns synchronously; the underlying subscription attaches once the
   *  runtime loads, and `close()` before then cancels it.
   */
  on(table, handlers, opts) {
    const group = opts && opts.group;
    if (!group) throw new Error("umbral: .on(...) requires opts.group — the group you expose(...)-d to");
    // SSR / non-browser: degrade to a no-op subscription, matching the realtime
    // runtime's own posture (no transport → a no-op unsubscribe, no noise). A
    // component that subscribes on mount then renders on the server must not
    // throw or log.
    if (typeof document === "undefined") return { close() {} };
    let sub = null;
    let closed = false;
    this._realtime()
      .then((rt) => {
        if (closed) return;
        sub = rt.model(String(table), handlers || {}, { group });
      })
      .catch((err) => {
        if (typeof console !== "undefined" && console.error) console.error(err);
      });
    return {
      close() {
        closed = true;
        if (sub) { try { sub.unsubscribe(); } catch (_) {} sub = null; }
      },
    };
  }

  /** @internal Load the realtime runtime once, memoised. It is a classic
   *  script (sets `window.umbral.realtime`), so it is injected via a script tag
   *  — that works cross-origin without CORS, unlike a dynamic `import()`. */
  _realtime() {
    const g = globalThis;
    if (g.umbral && g.umbral.realtime) return Promise.resolve(g.umbral.realtime);
    if (this._rt) return this._rt;
    if (typeof document === "undefined") {
      return Promise.reject(new Error("umbral: realtime requires a browser environment"));
    }
    const src = `${this.baseUrl}${this.realtimePath}/client.js`;
    this._rt = new Promise((resolve, reject) => {
      const done = () => {
        if (g.umbral && g.umbral.realtime) resolve(g.umbral.realtime);
        else reject(new Error(`umbral: loaded ${src} but umbral.realtime is missing`));
      };
      let el = document.querySelector('script[data-umbral-realtime]');
      if (!el) {
        el = document.createElement("script");
        el.src = src;
        el.async = true;
        el.setAttribute("data-umbral-realtime", "");
        el.addEventListener("load", done);
        el.addEventListener("error", () =>
          reject(new Error(`umbral: failed to load ${src} — is RealtimePlugin mounted at ${this.realtimePath}?`)));
        document.head.appendChild(el);
      } else {
        el.addEventListener("load", done);
        el.addEventListener("error", () => reject(new Error(`umbral: failed to load ${src}`)));
        done();
      }
    });
    return this._rt;
  }

  /** @internal */
  async _request(method, path, body) {
    const doFetch = this.opts.fetch ?? fetch;
    const headers = { "Accept": "application/json", ...this.opts.headers };
    // Auth, in ascending precedence: static token, static apiKey, then the
    // dynamic hook (so a fresh JWT overrides a stale static one). Defaults for
    // the prefix / header come from your API's declared security scheme.
    if (this._token) {
      headers["Authorization"] = `${this.opts.tokenPrefix ?? "Bearer"} ${this._token}`;
    }
    if (this.opts.apiKey) {
      headers[this.opts.apiKeyHeader ?? "X-API-Key"] = this.opts.apiKey;
    }
    if (this.opts.getAuthHeaders) {
      Object.assign(headers, await this.opts.getAuthHeaders());
    }
    const init = { method, headers };
    const credentials = this.opts.credentials ?? "include";
    if (credentials) init.credentials = credentials;
    if (body !== undefined) {
      headers["Content-Type"] = "application/json";
      init.body = JSON.stringify(body);
    }
    const res = await doFetch(this.baseUrl + path, init);
    const parsed = res.status === 204 ? null : await res.json().catch(() => null);
    if (!res.ok) throw new UmbralError(res.status, parsed);
    return parsed;
  }
}
