// Code generated by `umbral gen-client`. DO NOT EDIT.
//
// client.d.ts — the types
//
// Regenerate after any model or REST-resource change:
//     cargo run -- gen-client --out <this directory>
//
// Base path: /api. Auth: Bearer token / apiKey (X-API-Key) / session cookie.

// Code generated by `umbral typegen`. DO NOT EDIT.
//
// Regenerate after any model change:
//     cargo run -- typegen --out <this file>
//
// These describe the JSON umbral puts on the wire: the model struct as serde
// serialises it. Field names are snake_case because the wire is snake_case.
// A `ForeignKey<T>` is the target's primary-key value, not a nested object.

/** `project` = Project, `task` = Task, `direct` = Direct, `incident` = Incident */
export type TaskflowAgentChannelKind = "project" | "task" | "direct" | "incident";

/** `user` = User, `agent` = Agent */
export type TaskflowAgentChannelMemberMemberKind = "user" | "agent";

/** `active` = Active, `revoked` = Revoked, `expired` = Expired */
export type TaskflowAgentCredentialStatus = "active" | "revoked" | "expired";

/** `normal` = Normal, `important` = Important, `urgent` = Urgent */
export type TaskflowAgentMessagePriority = "normal" | "important" | "urgent";

/** `user` = User, `agent` = Agent */
export type TaskflowAgentMessageSenderKind = "user" | "agent";

/** `connected` = Connected, `disconnected` = Disconnected, `expired` = Expired */
export type TaskflowAgentSessionStatus = "connected" | "disconnected" | "expired";

/** `offline` = Offline, `connected` = Connected, `idle` = Idle, `busy` = Busy, `blocked` = Blocked, `revoked` = Revoked */
export type TaskflowAgentStatus = "offline" | "connected" | "idle" | "busy" | "blocked" | "revoked";

/** `stdout` = Stdout, `stderr` = Stderr, `stdin` = Stdin, `system` = System */
export type TaskflowAgentTerminalFrameStream = "stdout" | "stderr" | "stdin" | "system";

/** `user` = User, `agent` = Agent */
export type TaskflowChannelReadCursorMemberKind = "user" | "agent";

/** `local` = Local, `preview` = Preview, `staging` = Staging, `production` = Production */
export type TaskflowProjectApiEndpointEnvironment = "local" | "preview" | "staging" | "production";

/** `unknown` = Unknown, `healthy` = Healthy, `degraded` = Degraded, `down` = Down */
export type TaskflowProjectApiEndpointHealth = "unknown" | "healthy" | "degraded" | "down";

/** `owner` = Owner, `admin` = Admin, `developer` = Developer, `reviewer` = Reviewer, `viewer` = Viewer */
export type TaskflowProjectInviteRole = "owner" | "admin" | "developer" | "reviewer" | "viewer";

/** `pending` = Pending, `accepted` = Accepted, `declined` = Declined, `revoked` = Revoked, `expired` = Expired */
export type TaskflowProjectInviteStatus = "pending" | "accepted" | "declined" | "revoked" | "expired";

/** `owner` = Owner, `admin` = Admin, `developer` = Developer, `reviewer` = Reviewer, `viewer` = Viewer */
export type TaskflowProjectMemberRole = "owner" | "admin" | "developer" | "reviewer" | "viewer";

/** `invited` = Invited, `active` = Active, `suspended` = Suspended, `left` = Left */
export type TaskflowProjectMemberStatus = "invited" | "active" | "suspended" | "left";

/** `active` = Active, `paused` = Paused, `archived` = Archived */
export type TaskflowProjectStatus = "active" | "paused" | "archived";

/** `user` = User, `agent` = Agent, `system` = System */
export type TaskflowTaskActivityActorKind = "user" | "agent" | "system";

/** `low` = Low, `normal` = Normal, `high` = High, `critical` = Critical */
export type TaskflowTaskPriority = "low" | "normal" | "high" | "critical";

/** `blocks` = Blocks, `related_to` = RelatedTo, `duplicates` = Duplicates, `parent_child` = ParentChild */
export type TaskflowTaskRelationKind = "blocks" | "related_to" | "duplicates" | "parent_child";

/** `approved` = Approved, `changes_requested` = ChangesRequested */
export type TaskflowTaskReviewDecision = "approved" | "changes_requested";

/** `user` = User, `agent` = Agent */
export type TaskflowTaskReviewReviewerKind = "user" | "agent";

/** `user` = User, `agent` = Agent, `system` = System */
export type TaskflowTaskSessionActorKind = "user" | "agent" | "system";

/** `running` = Running, `paused` = Paused, `stopped` = Stopped, `failed` = Failed */
export type TaskflowTaskSessionState = "running" | "paused" | "stopped" | "failed";

/** `not_started` = NotStarted, `in_progress` = InProgress, `paused` = Paused, `blocked` = Blocked, `partial_done` = PartialDone, `done` = Done, `archived` = Archived */
export type TaskflowTaskStatus = "not_started" | "in_progress" | "paused" | "blocked" | "partial_done" | "done" | "archived";

/** `light` = Light, `dark` = Dark, `system` = System */
export type TaskflowUserSettingsTheme = "light" | "dark" | "system";

/**
 * User preference
 * Table `admin_user_pref`, from the `app` plugin.
 */
export interface AdminUserPref {
  id: number;
  user_id: number;
  theme: string;
  density: string;
  sidebar_collapsed: boolean;
  dashboard_layout: string;
  preferences: string | null;
  updated_at: string;
}

/** Table `auth_challenge`, from the `app` plugin. */
export interface AuthChallenge {
  id: number;
  /** Foreign key into `auth_user`. */
  user_id: number;
  purpose: string;
  secret_hash: string;
  expires_at: string;
  attempts: number;
  used_at: string | null;
  created_at: string;
}

/** Table `auth_token`, from the `app` plugin. */
export interface AuthToken {
  id: number;
  /** Foreign key into `auth_user`. */
  user_id: number;
  key_hash: string;
  name: string;
  created_at: string;
  last_used_at: string | null;
}

/**
 * Media file
 * Table `media_file`, from the `app` plugin.
 */
export interface MediaFile {
  id: number;
  key: string;
  filename: string;
  content_type: string;
  size: number;
  uploaded_at: string;
  status: string;
}

/** Table `post`, from the `app` plugin. */
export interface Post {
  id: number;
  title: string;
  body: string;
  published: boolean;
  /** Foreign key into `auth_user`. */
  author: number;
  created_at: string | null;
}

/** Table `taskflow_agent`, from the `app` plugin. */
export interface TaskflowAgent {
  id: number;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  project: number;
  display_name: string;
  identifier: string;
  fingerprint: string | null;
  project_root: string | null;
  taskflow_file_path: string | null;
  runtime: string | null;
  version: string | null;
  status: TaskflowAgentStatus;
  /** Foreign key into `auth_user`. */
  linked_by: number | null;
  linked_user_label: string | null;
  last_seen_at: string | null;
  created_at: string | null;
}

/** Table `taskflow_agent_channel`, from the `app` plugin. */
export interface TaskflowAgentChannel {
  id: number;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  project: number;
  title: string;
  topic: string | null;
  kind: TaskflowAgentChannelKind;
  /** Foreign key: the `id` of a TaskflowTask (`taskflow_task`). */
  task: number | null;
  /** Foreign key into `auth_user`. */
  created_by_user: number | null;
  /** Foreign key: the `id` of a TaskflowAgent (`taskflow_agent`). */
  created_by_agent: number | null;
  archived: boolean;
  created_at: string | null;
}

/** Table `taskflow_agent_channel_member`, from the `app` plugin. */
export interface TaskflowAgentChannelMember {
  id: number;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  project: number;
  /** Foreign key: the `id` of a TaskflowAgentChannel (`taskflow_agent_channel`). */
  channel: number;
  member_kind: TaskflowAgentChannelMemberMemberKind;
  /** Foreign key into `auth_user`. */
  user: number | null;
  /** Foreign key: the `id` of a TaskflowAgent (`taskflow_agent`). */
  agent: number | null;
  display_name: string;
  role: string;
  joined_at: string | null;
}

/** Table `taskflow_agent_credential`, from the `app` plugin. */
export interface TaskflowAgentCredential {
  id: number;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  project: number;
  /** Foreign key: the `id` of a TaskflowAgent (`taskflow_agent`). */
  agent: number | null;
  /** Foreign key into `auth_user`. */
  issued_by: number | null;
  name: string;
  key_prefix: string;
  key_hash: string;
  status: TaskflowAgentCredentialStatus;
  expires_at: string | null;
  revoked_at: string | null;
  created_at: string | null;
}

/** Table `taskflow_agent_message`, from the `app` plugin. */
export interface TaskflowAgentMessage {
  id: number;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  project: number;
  /** Foreign key: the `id` of a TaskflowAgentChannel (`taskflow_agent_channel`). */
  channel: number;
  /** Foreign key: the `id` of a TaskflowTask (`taskflow_task`). */
  task: number | null;
  sender_kind: TaskflowAgentMessageSenderKind;
  /** Foreign key into `auth_user`. */
  sender_user: number | null;
  /** Foreign key: the `id` of a TaskflowAgent (`taskflow_agent`). */
  sender_agent: number | null;
  sender_label: string;
  body_markdown: string;
  priority: TaskflowAgentMessagePriority;
  client_nonce: string | null;
  created_at: string | null;
}

/** Table `taskflow_agent_session`, from the `app` plugin. */
export interface TaskflowAgentSession {
  id: number;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  project: number;
  /** Foreign key: the `id` of a TaskflowAgent (`taskflow_agent`). */
  agent: number;
  /** Foreign key into `auth_user`. */
  connected_by: number | null;
  session_identifier: string;
  host: string | null;
  pid: number | null;
  cwd: string | null;
  transport: string | null;
  status: TaskflowAgentSessionStatus;
  connected_at: string;
  last_seen_at: string | null;
  disconnected_at: string | null;
  created_at: string | null;
}

/** Table `taskflow_agent_terminal_frame`, from the `app` plugin. */
export interface TaskflowAgentTerminalFrame {
  id: number;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  project: number;
  /** Foreign key: the `id` of a TaskflowAgent (`taskflow_agent`). */
  agent: number;
  /** Foreign key: the `id` of a TaskflowAgentSession (`taskflow_agent_session`). */
  session: number | null;
  /** Foreign key: the `id` of a TaskflowTask (`taskflow_task`). */
  task: number | null;
  stream: TaskflowAgentTerminalFrameStream;
  sequence: number;
  content: string;
  created_at: string | null;
}

/** Table `taskflow_channel_read_cursor`, from the `app` plugin. */
export interface TaskflowChannelReadCursor {
  id: number;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  project: number;
  /** Foreign key: the `id` of a TaskflowAgentChannel (`taskflow_agent_channel`). */
  channel: number;
  member_kind: TaskflowChannelReadCursorMemberKind;
  /** Foreign key into `auth_user`. */
  member_user: number | null;
  /** Foreign key: the `id` of a TaskflowAgent (`taskflow_agent`). */
  member_agent: number | null;
  /** Foreign key: the `id` of a TaskflowAgentMessage (`taskflow_agent_message`). */
  last_read_message: number | null;
  last_read_at: string;
  created_at: string | null;
}

/** Table `taskflow_message_attachment`, from the `app` plugin. */
export interface TaskflowMessageAttachment {
  id: number;
  /** Foreign key: the `id` of a TaskflowAgentMessage (`taskflow_agent_message`). */
  message: number;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  project: number;
  file: string;
  name: string;
  content_type: string;
  size_bytes: number;
  created_at: string | null;
}

/** Table `taskflow_project`, from the `app` plugin. */
export interface TaskflowProject {
  id: number;
  name: string;
  slug: string;
  description_markdown: string;
  repository_url: string | null;
  default_api_base_url: string | null;
  status: TaskflowProjectStatus;
  /** Foreign key into `auth_user`. */
  owner: number | null;
  created_at: string | null;
  updated_at: string | null;
}

/** Table `taskflow_project_api_endpoint`, from the `app` plugin. */
export interface TaskflowProjectApiEndpoint {
  id: number;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  project: number;
  label: string;
  base_url: string;
  environment: TaskflowProjectApiEndpointEnvironment;
  health: TaskflowProjectApiEndpointHealth;
  is_default: boolean;
  notes_markdown: string | null;
  last_checked_at: string | null;
  created_at: string | null;
}

/** Table `taskflow_project_invite`, from the `app` plugin. */
export interface TaskflowProjectInvite {
  id: number;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  project: number;
  email: string;
  display_name: string | null;
  role: TaskflowProjectInviteRole;
  status: TaskflowProjectInviteStatus;
  invite_token: string;
  /** Foreign key into `auth_user`. */
  invited_by: number | null;
  expires_at: string | null;
  accepted_at: string | null;
  created_at: string | null;
}

/** Table `taskflow_project_member`, from the `app` plugin. */
export interface TaskflowProjectMember {
  id: number;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  project: number;
  member_key: string;
  /** Foreign key into `auth_user`. */
  user: number | null;
  display_name: string;
  email: string | null;
  role: TaskflowProjectMemberRole;
  status: TaskflowProjectMemberStatus;
  /** Foreign key into `auth_user`. */
  invited_by: number | null;
  created_at: string | null;
  joined_at: string | null;
}

/** Table `taskflow_task`, from the `app` plugin. */
export interface TaskflowTask {
  id: number;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  project: number;
  title: string;
  description_markdown: string;
  notes_markdown: string | null;
  status: TaskflowTaskStatus;
  priority: TaskflowTaskPriority;
  sort_order: number;
  /** Foreign key into `auth_user`. */
  created_by: number | null;
  /** Foreign key into `auth_user`. */
  assigned_user: number | null;
  assigned_agent_id: number | null;
  assignee_label: string | null;
  due_at: string | null;
  created_at: string | null;
  updated_at: string | null;
}

/** Table `taskflow_task_activity`, from the `app` plugin. */
export interface TaskflowTaskActivity {
  id: number;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  project: number;
  /** Foreign key: the `id` of a TaskflowTask (`taskflow_task`). */
  task: number | null;
  actor_kind: TaskflowTaskActivityActorKind;
  /** Foreign key into `auth_user`. */
  actor_user: number | null;
  actor_agent_id: number | null;
  actor_label: string;
  action: string;
  body_markdown: string | null;
  metadata_json: string | null;
  created_at: string | null;
}

/** Table `taskflow_task_relation`, from the `app` plugin. */
export interface TaskflowTaskRelation {
  id: number;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  project: number;
  /** Foreign key: the `id` of a TaskflowTask (`taskflow_task`). */
  source_task: number;
  /** Foreign key: the `id` of a TaskflowTask (`taskflow_task`). */
  target_task: number;
  kind: TaskflowTaskRelationKind;
  detail_markdown: string | null;
  created_at: string | null;
}

/** Table `taskflow_task_review`, from the `app` plugin. */
export interface TaskflowTaskReview {
  id: number;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  project: number;
  /** Foreign key: the `id` of a TaskflowTask (`taskflow_task`). */
  task: number;
  reviewer_kind: TaskflowTaskReviewReviewerKind;
  /** Foreign key into `auth_user`. */
  reviewer_user: number | null;
  /** Foreign key: the `id` of a TaskflowAgent (`taskflow_agent`). */
  reviewer_agent: number | null;
  reviewer_label: string;
  decision: TaskflowTaskReviewDecision;
  body_markdown: string | null;
  created_at: string | null;
}

/** Table `taskflow_task_session`, from the `app` plugin. */
export interface TaskflowTaskSession {
  id: number;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  project: number;
  /** Foreign key: the `id` of a TaskflowTask (`taskflow_task`). */
  task: number;
  state: TaskflowTaskSessionState;
  actor_kind: TaskflowTaskSessionActorKind;
  /** Foreign key into `auth_user`. */
  actor_user: number | null;
  actor_agent_id: number | null;
  actor_label: string;
  started_at: string;
  ended_at: string | null;
  duration_seconds: number | null;
  summary_markdown: string | null;
  created_at: string | null;
}

/** Table `taskflow_user_settings`, from the `app` plugin. */
export interface TaskflowUserSettings {
  id: number;
  /** Foreign key into `auth_user`. */
  user: number;
  theme: TaskflowUserSettingsTheme;
  email_notifications: boolean;
  /** Foreign key: the `id` of a TaskflowProject (`taskflow_project`). */
  default_project: number | null;
  created_at: string | null;
  updated_at: string | null;
}

/** Filterable query parameters for `admin_user_pref`. Every key is optional and AND-combined server-side. */
export interface AdminUserPrefFilters {
  "user_id"?: number;
  "user_id__ne"?: number;
  "user_id__gte"?: number;
  "user_id__lte"?: number;
  "user_id__gt"?: number;
  "user_id__lt"?: number;
  "user_id__in"?: number[];
  "theme"?: string;
  "theme__ne"?: string;
  "theme__contains"?: string;
  "theme__icontains"?: string;
  "theme__startswith"?: string;
  "theme__in"?: string[];
  "density"?: string;
  "density__ne"?: string;
  "density__contains"?: string;
  "density__icontains"?: string;
  "density__startswith"?: string;
  "density__in"?: string[];
  "sidebar_collapsed"?: boolean;
  "sidebar_collapsed__ne"?: boolean;
  "sidebar_collapsed__in"?: boolean[];
  "dashboard_layout"?: string;
  "dashboard_layout__ne"?: string;
  "dashboard_layout__contains"?: string;
  "dashboard_layout__icontains"?: string;
  "dashboard_layout__startswith"?: string;
  "dashboard_layout__in"?: string[];
  "preferences"?: string;
  "preferences__ne"?: string;
  "preferences__contains"?: string;
  "preferences__icontains"?: string;
  "preferences__startswith"?: string;
  "preferences__in"?: string[];
  "preferences__isnull"?: boolean;
  "updated_at"?: string;
  "updated_at__ne"?: string;
  "updated_at__gte"?: string;
  "updated_at__lte"?: string;
  "updated_at__gt"?: string;
  "updated_at__lt"?: string;
  "updated_at__in"?: string[];
}
export type AdminUserPrefOrdering = "id" | "-id" | "user_id" | "-user_id" | "theme" | "-theme" | "density" | "-density" | "sidebar_collapsed" | "-sidebar_collapsed" | "dashboard_layout" | "-dashboard_layout" | "preferences" | "-preferences" | "updated_at" | "-updated_at";
/** Body for creating a `admin_user_pref`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface AdminUserPrefCreate {
  user_id: number;
  theme: string;
  density: string;
  sidebar_collapsed: boolean;
  dashboard_layout: string;
  preferences?: string | null;
  updated_at: string;
}
/** Body for updating a `admin_user_pref` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface AdminUserPrefUpdate {
}

/** Filterable query parameters for `auth_challenge`. Every key is optional and AND-combined server-side. */
export interface AuthChallengeFilters {
  "user_id"?: number;
  "user_id__ne"?: number;
  "user_id__in"?: number[];
  "purpose"?: string;
  "purpose__ne"?: string;
  "purpose__contains"?: string;
  "purpose__icontains"?: string;
  "purpose__startswith"?: string;
  "purpose__in"?: string[];
  "secret_hash"?: string;
  "secret_hash__ne"?: string;
  "secret_hash__contains"?: string;
  "secret_hash__icontains"?: string;
  "secret_hash__startswith"?: string;
  "secret_hash__in"?: string[];
  "expires_at"?: string;
  "expires_at__ne"?: string;
  "expires_at__gte"?: string;
  "expires_at__lte"?: string;
  "expires_at__gt"?: string;
  "expires_at__lt"?: string;
  "expires_at__in"?: string[];
  "attempts"?: number;
  "attempts__ne"?: number;
  "attempts__gte"?: number;
  "attempts__lte"?: number;
  "attempts__gt"?: number;
  "attempts__lt"?: number;
  "attempts__in"?: number[];
  "used_at"?: string;
  "used_at__ne"?: string;
  "used_at__gte"?: string;
  "used_at__lte"?: string;
  "used_at__gt"?: string;
  "used_at__lt"?: string;
  "used_at__in"?: string[];
  "used_at__isnull"?: boolean;
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
}
export type AuthChallengeOrdering = "id" | "-id" | "user_id" | "-user_id" | "purpose" | "-purpose" | "secret_hash" | "-secret_hash" | "expires_at" | "-expires_at" | "attempts" | "-attempts" | "used_at" | "-used_at" | "created_at" | "-created_at";
/** Body for creating a `auth_challenge`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface AuthChallengeCreate {
  user_id: number;
  purpose: string;
  secret_hash: string;
  expires_at: string;
  attempts: number;
  used_at?: string | null;
  created_at: string;
}
/** Body for updating a `auth_challenge` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface AuthChallengeUpdate {
  user_id?: number;
  purpose?: string;
  secret_hash?: string;
  expires_at?: string;
  attempts?: number;
  used_at?: string | null;
  created_at?: string;
}

/** Filterable query parameters for `auth_token`. Every key is optional and AND-combined server-side. */
export interface AuthTokenFilters {
  "user_id"?: number;
  "user_id__ne"?: number;
  "user_id__in"?: number[];
  "key_hash"?: string;
  "key_hash__ne"?: string;
  "key_hash__contains"?: string;
  "key_hash__icontains"?: string;
  "key_hash__startswith"?: string;
  "key_hash__in"?: string[];
  "name"?: string;
  "name__ne"?: string;
  "name__contains"?: string;
  "name__icontains"?: string;
  "name__startswith"?: string;
  "name__in"?: string[];
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "last_used_at"?: string;
  "last_used_at__ne"?: string;
  "last_used_at__gte"?: string;
  "last_used_at__lte"?: string;
  "last_used_at__gt"?: string;
  "last_used_at__lt"?: string;
  "last_used_at__in"?: string[];
  "last_used_at__isnull"?: boolean;
}
export type AuthTokenOrdering = "id" | "-id" | "user_id" | "-user_id" | "key_hash" | "-key_hash" | "name" | "-name" | "created_at" | "-created_at" | "last_used_at" | "-last_used_at";
/** Body for creating a `auth_token`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface AuthTokenCreate {
  user_id: number;
  key_hash: string;
  name: string;
  created_at: string;
  last_used_at?: string | null;
}
/** Body for updating a `auth_token` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface AuthTokenUpdate {
  user_id?: number;
  key_hash?: string;
  name?: string;
  created_at?: string;
  last_used_at?: string | null;
}

/** Filterable query parameters for `media_file`. Every key is optional and AND-combined server-side. */
export interface MediaFileFilters {
  "key"?: string;
  "key__ne"?: string;
  "key__contains"?: string;
  "key__icontains"?: string;
  "key__startswith"?: string;
  "key__in"?: string[];
  "filename"?: string;
  "filename__ne"?: string;
  "filename__contains"?: string;
  "filename__icontains"?: string;
  "filename__startswith"?: string;
  "filename__in"?: string[];
  "content_type"?: string;
  "content_type__ne"?: string;
  "content_type__contains"?: string;
  "content_type__icontains"?: string;
  "content_type__startswith"?: string;
  "content_type__in"?: string[];
  "size"?: number;
  "size__ne"?: number;
  "size__gte"?: number;
  "size__lte"?: number;
  "size__gt"?: number;
  "size__lt"?: number;
  "size__in"?: number[];
  "uploaded_at"?: string;
  "uploaded_at__ne"?: string;
  "uploaded_at__gte"?: string;
  "uploaded_at__lte"?: string;
  "uploaded_at__gt"?: string;
  "uploaded_at__lt"?: string;
  "uploaded_at__in"?: string[];
  "status"?: string;
  "status__ne"?: string;
  "status__contains"?: string;
  "status__icontains"?: string;
  "status__startswith"?: string;
  "status__in"?: string[];
}
export type MediaFileOrdering = "id" | "-id" | "key" | "-key" | "filename" | "-filename" | "content_type" | "-content_type" | "size" | "-size" | "uploaded_at" | "-uploaded_at" | "status" | "-status";
/** Body for creating a `media_file`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface MediaFileCreate {
  key: string;
  filename: string;
  content_type: string;
  size: number;
  uploaded_at: string;
  status?: string;
}
/** Body for updating a `media_file` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface MediaFileUpdate {
}

/** Filterable query parameters for `post`. Every key is optional and AND-combined server-side. */
export interface PostFilters {
  "title"?: string;
  "title__ne"?: string;
  "title__contains"?: string;
  "title__icontains"?: string;
  "title__startswith"?: string;
  "title__in"?: string[];
  "body"?: string;
  "body__ne"?: string;
  "body__contains"?: string;
  "body__icontains"?: string;
  "body__startswith"?: string;
  "body__in"?: string[];
  "published"?: boolean;
  "published__ne"?: boolean;
  "published__in"?: boolean[];
  "author"?: number;
  "author__ne"?: number;
  "author__in"?: number[];
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
}
export type PostOrdering = "id" | "-id" | "title" | "-title" | "body" | "-body" | "published" | "-published" | "author" | "-author" | "created_at" | "-created_at";
/** Body for creating a `post`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface PostCreate {
  title: string;
  body: string;
  published: boolean;
  author: number;
  created_at?: string | null;
}
/** Body for updating a `post` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface PostUpdate {
  title?: string;
  body?: string;
  published?: boolean;
  author?: number;
  created_at?: string | null;
}

/** Filterable query parameters for `taskflow_agent`. Every key is optional and AND-combined server-side. */
export interface TaskflowAgentFilters {
  "project"?: number;
  "project__ne"?: number;
  "project__in"?: number[];
  "display_name"?: string;
  "display_name__ne"?: string;
  "display_name__contains"?: string;
  "display_name__icontains"?: string;
  "display_name__startswith"?: string;
  "display_name__in"?: string[];
  "identifier"?: string;
  "identifier__ne"?: string;
  "identifier__contains"?: string;
  "identifier__icontains"?: string;
  "identifier__startswith"?: string;
  "identifier__in"?: string[];
  "fingerprint"?: string;
  "fingerprint__ne"?: string;
  "fingerprint__contains"?: string;
  "fingerprint__icontains"?: string;
  "fingerprint__startswith"?: string;
  "fingerprint__in"?: string[];
  "fingerprint__isnull"?: boolean;
  "project_root"?: string;
  "project_root__ne"?: string;
  "project_root__contains"?: string;
  "project_root__icontains"?: string;
  "project_root__startswith"?: string;
  "project_root__in"?: string[];
  "project_root__isnull"?: boolean;
  "taskflow_file_path"?: string;
  "taskflow_file_path__ne"?: string;
  "taskflow_file_path__contains"?: string;
  "taskflow_file_path__icontains"?: string;
  "taskflow_file_path__startswith"?: string;
  "taskflow_file_path__in"?: string[];
  "taskflow_file_path__isnull"?: boolean;
  "runtime"?: string;
  "runtime__ne"?: string;
  "runtime__contains"?: string;
  "runtime__icontains"?: string;
  "runtime__startswith"?: string;
  "runtime__in"?: string[];
  "runtime__isnull"?: boolean;
  "version"?: string;
  "version__ne"?: string;
  "version__contains"?: string;
  "version__icontains"?: string;
  "version__startswith"?: string;
  "version__in"?: string[];
  "version__isnull"?: boolean;
  "status"?: TaskflowAgentStatus;
  "status__ne"?: TaskflowAgentStatus;
  "status__contains"?: string;
  "status__icontains"?: string;
  "status__startswith"?: string;
  "status__in"?: TaskflowAgentStatus[];
  "linked_by"?: number;
  "linked_by__ne"?: number;
  "linked_by__in"?: number[];
  "linked_by__isnull"?: boolean;
  "linked_user_label"?: string;
  "linked_user_label__ne"?: string;
  "linked_user_label__contains"?: string;
  "linked_user_label__icontains"?: string;
  "linked_user_label__startswith"?: string;
  "linked_user_label__in"?: string[];
  "linked_user_label__isnull"?: boolean;
  "last_seen_at"?: string;
  "last_seen_at__ne"?: string;
  "last_seen_at__gte"?: string;
  "last_seen_at__lte"?: string;
  "last_seen_at__gt"?: string;
  "last_seen_at__lt"?: string;
  "last_seen_at__in"?: string[];
  "last_seen_at__isnull"?: boolean;
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
}
export type TaskflowAgentOrdering = "id" | "-id" | "project" | "-project" | "display_name" | "-display_name" | "identifier" | "-identifier" | "fingerprint" | "-fingerprint" | "project_root" | "-project_root" | "taskflow_file_path" | "-taskflow_file_path" | "runtime" | "-runtime" | "version" | "-version" | "status" | "-status" | "linked_by" | "-linked_by" | "linked_user_label" | "-linked_user_label" | "last_seen_at" | "-last_seen_at" | "created_at" | "-created_at";
/** Body for creating a `taskflow_agent`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowAgentCreate {
  project: number;
  display_name: string;
  identifier: string;
  fingerprint?: string | null;
  project_root?: string | null;
  taskflow_file_path?: string | null;
  runtime?: string | null;
  version?: string | null;
  status?: TaskflowAgentStatus;
  linked_by?: number | null;
  linked_user_label?: string | null;
  last_seen_at?: string | null;
}
/** Body for updating a `taskflow_agent` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowAgentUpdate {
  project?: number;
  display_name?: string;
  identifier?: string;
  fingerprint?: string | null;
  project_root?: string | null;
  taskflow_file_path?: string | null;
  runtime?: string | null;
  version?: string | null;
  status?: TaskflowAgentStatus;
  linked_by?: number | null;
  linked_user_label?: string | null;
  last_seen_at?: string | null;
}

/** Filterable query parameters for `taskflow_agent_channel`. Every key is optional and AND-combined server-side. */
export interface TaskflowAgentChannelFilters {
  "project"?: number;
  "project__ne"?: number;
  "project__in"?: number[];
  "title"?: string;
  "title__ne"?: string;
  "title__contains"?: string;
  "title__icontains"?: string;
  "title__startswith"?: string;
  "title__in"?: string[];
  "topic"?: string;
  "topic__ne"?: string;
  "topic__contains"?: string;
  "topic__icontains"?: string;
  "topic__startswith"?: string;
  "topic__in"?: string[];
  "topic__isnull"?: boolean;
  "kind"?: TaskflowAgentChannelKind;
  "kind__ne"?: TaskflowAgentChannelKind;
  "kind__contains"?: string;
  "kind__icontains"?: string;
  "kind__startswith"?: string;
  "kind__in"?: TaskflowAgentChannelKind[];
  "task"?: number;
  "task__ne"?: number;
  "task__in"?: number[];
  "task__isnull"?: boolean;
  "created_by_user"?: number;
  "created_by_user__ne"?: number;
  "created_by_user__in"?: number[];
  "created_by_user__isnull"?: boolean;
  "created_by_agent"?: number;
  "created_by_agent__ne"?: number;
  "created_by_agent__in"?: number[];
  "created_by_agent__isnull"?: boolean;
  "archived"?: boolean;
  "archived__ne"?: boolean;
  "archived__in"?: boolean[];
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
}
export type TaskflowAgentChannelOrdering = "id" | "-id" | "project" | "-project" | "title" | "-title" | "topic" | "-topic" | "kind" | "-kind" | "task" | "-task" | "created_by_user" | "-created_by_user" | "created_by_agent" | "-created_by_agent" | "archived" | "-archived" | "created_at" | "-created_at";
/** Body for creating a `taskflow_agent_channel`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowAgentChannelCreate {
  project: number;
  title: string;
  topic?: string | null;
  kind?: TaskflowAgentChannelKind;
  task?: number | null;
  created_by_user?: number | null;
  created_by_agent?: number | null;
  archived?: boolean;
}
/** Body for updating a `taskflow_agent_channel` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowAgentChannelUpdate {
  project?: number;
  title?: string;
  topic?: string | null;
  kind?: TaskflowAgentChannelKind;
  task?: number | null;
  created_by_user?: number | null;
  created_by_agent?: number | null;
  archived?: boolean;
}

/** Filterable query parameters for `taskflow_agent_channel_member`. Every key is optional and AND-combined server-side. */
export interface TaskflowAgentChannelMemberFilters {
  "project"?: number;
  "project__ne"?: number;
  "project__in"?: number[];
  "channel"?: number;
  "channel__ne"?: number;
  "channel__in"?: number[];
  "member_kind"?: TaskflowAgentChannelMemberMemberKind;
  "member_kind__ne"?: TaskflowAgentChannelMemberMemberKind;
  "member_kind__contains"?: string;
  "member_kind__icontains"?: string;
  "member_kind__startswith"?: string;
  "member_kind__in"?: TaskflowAgentChannelMemberMemberKind[];
  "user"?: number;
  "user__ne"?: number;
  "user__in"?: number[];
  "user__isnull"?: boolean;
  "agent"?: number;
  "agent__ne"?: number;
  "agent__in"?: number[];
  "agent__isnull"?: boolean;
  "display_name"?: string;
  "display_name__ne"?: string;
  "display_name__contains"?: string;
  "display_name__icontains"?: string;
  "display_name__startswith"?: string;
  "display_name__in"?: string[];
  "role"?: string;
  "role__ne"?: string;
  "role__contains"?: string;
  "role__icontains"?: string;
  "role__startswith"?: string;
  "role__in"?: string[];
  "joined_at"?: string;
  "joined_at__ne"?: string;
  "joined_at__gte"?: string;
  "joined_at__lte"?: string;
  "joined_at__gt"?: string;
  "joined_at__lt"?: string;
  "joined_at__in"?: string[];
  "joined_at__isnull"?: boolean;
}
export type TaskflowAgentChannelMemberOrdering = "id" | "-id" | "project" | "-project" | "channel" | "-channel" | "member_kind" | "-member_kind" | "user" | "-user" | "agent" | "-agent" | "display_name" | "-display_name" | "role" | "-role" | "joined_at" | "-joined_at";
/** Body for creating a `taskflow_agent_channel_member`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowAgentChannelMemberCreate {
  project: number;
  channel: number;
  member_kind?: TaskflowAgentChannelMemberMemberKind;
  user?: number | null;
  agent?: number | null;
  display_name: string;
  role: string;
}
/** Body for updating a `taskflow_agent_channel_member` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowAgentChannelMemberUpdate {
  project?: number;
  channel?: number;
  member_kind?: TaskflowAgentChannelMemberMemberKind;
  user?: number | null;
  agent?: number | null;
  display_name?: string;
  role?: string;
}

/** Filterable query parameters for `taskflow_agent_credential`. Every key is optional and AND-combined server-side. */
export interface TaskflowAgentCredentialFilters {
  "project"?: number;
  "project__ne"?: number;
  "project__in"?: number[];
  "agent"?: number;
  "agent__ne"?: number;
  "agent__in"?: number[];
  "agent__isnull"?: boolean;
  "issued_by"?: number;
  "issued_by__ne"?: number;
  "issued_by__in"?: number[];
  "issued_by__isnull"?: boolean;
  "name"?: string;
  "name__ne"?: string;
  "name__contains"?: string;
  "name__icontains"?: string;
  "name__startswith"?: string;
  "name__in"?: string[];
  "key_prefix"?: string;
  "key_prefix__ne"?: string;
  "key_prefix__contains"?: string;
  "key_prefix__icontains"?: string;
  "key_prefix__startswith"?: string;
  "key_prefix__in"?: string[];
  "key_hash"?: string;
  "key_hash__ne"?: string;
  "key_hash__contains"?: string;
  "key_hash__icontains"?: string;
  "key_hash__startswith"?: string;
  "key_hash__in"?: string[];
  "status"?: TaskflowAgentCredentialStatus;
  "status__ne"?: TaskflowAgentCredentialStatus;
  "status__contains"?: string;
  "status__icontains"?: string;
  "status__startswith"?: string;
  "status__in"?: TaskflowAgentCredentialStatus[];
  "expires_at"?: string;
  "expires_at__ne"?: string;
  "expires_at__gte"?: string;
  "expires_at__lte"?: string;
  "expires_at__gt"?: string;
  "expires_at__lt"?: string;
  "expires_at__in"?: string[];
  "expires_at__isnull"?: boolean;
  "revoked_at"?: string;
  "revoked_at__ne"?: string;
  "revoked_at__gte"?: string;
  "revoked_at__lte"?: string;
  "revoked_at__gt"?: string;
  "revoked_at__lt"?: string;
  "revoked_at__in"?: string[];
  "revoked_at__isnull"?: boolean;
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
}
export type TaskflowAgentCredentialOrdering = "id" | "-id" | "project" | "-project" | "agent" | "-agent" | "issued_by" | "-issued_by" | "name" | "-name" | "key_prefix" | "-key_prefix" | "key_hash" | "-key_hash" | "status" | "-status" | "expires_at" | "-expires_at" | "revoked_at" | "-revoked_at" | "created_at" | "-created_at";
/** Body for creating a `taskflow_agent_credential`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowAgentCredentialCreate {
  project: number;
  agent?: number | null;
  issued_by?: number | null;
  name: string;
  key_prefix: string;
  key_hash: string;
  status?: TaskflowAgentCredentialStatus;
  expires_at?: string | null;
  revoked_at?: string | null;
}
/** Body for updating a `taskflow_agent_credential` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowAgentCredentialUpdate {
  project?: number;
  agent?: number | null;
  issued_by?: number | null;
  name?: string;
  key_prefix?: string;
  key_hash?: string;
  status?: TaskflowAgentCredentialStatus;
  expires_at?: string | null;
  revoked_at?: string | null;
}

/** Filterable query parameters for `taskflow_agent_message`. Every key is optional and AND-combined server-side. */
export interface TaskflowAgentMessageFilters {
  "project"?: number;
  "project__ne"?: number;
  "project__in"?: number[];
  "channel"?: number;
  "channel__ne"?: number;
  "channel__in"?: number[];
  "task"?: number;
  "task__ne"?: number;
  "task__in"?: number[];
  "task__isnull"?: boolean;
  "sender_kind"?: TaskflowAgentMessageSenderKind;
  "sender_kind__ne"?: TaskflowAgentMessageSenderKind;
  "sender_kind__contains"?: string;
  "sender_kind__icontains"?: string;
  "sender_kind__startswith"?: string;
  "sender_kind__in"?: TaskflowAgentMessageSenderKind[];
  "sender_user"?: number;
  "sender_user__ne"?: number;
  "sender_user__in"?: number[];
  "sender_user__isnull"?: boolean;
  "sender_agent"?: number;
  "sender_agent__ne"?: number;
  "sender_agent__in"?: number[];
  "sender_agent__isnull"?: boolean;
  "sender_label"?: string;
  "sender_label__ne"?: string;
  "sender_label__contains"?: string;
  "sender_label__icontains"?: string;
  "sender_label__startswith"?: string;
  "sender_label__in"?: string[];
  "body_markdown"?: string;
  "body_markdown__ne"?: string;
  "body_markdown__contains"?: string;
  "body_markdown__icontains"?: string;
  "body_markdown__startswith"?: string;
  "body_markdown__in"?: string[];
  "priority"?: TaskflowAgentMessagePriority;
  "priority__ne"?: TaskflowAgentMessagePriority;
  "priority__contains"?: string;
  "priority__icontains"?: string;
  "priority__startswith"?: string;
  "priority__in"?: TaskflowAgentMessagePriority[];
  "client_nonce"?: string;
  "client_nonce__ne"?: string;
  "client_nonce__contains"?: string;
  "client_nonce__icontains"?: string;
  "client_nonce__startswith"?: string;
  "client_nonce__in"?: string[];
  "client_nonce__isnull"?: boolean;
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
}
export type TaskflowAgentMessageOrdering = "id" | "-id" | "project" | "-project" | "channel" | "-channel" | "task" | "-task" | "sender_kind" | "-sender_kind" | "sender_user" | "-sender_user" | "sender_agent" | "-sender_agent" | "sender_label" | "-sender_label" | "body_markdown" | "-body_markdown" | "priority" | "-priority" | "client_nonce" | "-client_nonce" | "created_at" | "-created_at";
/** Body for creating a `taskflow_agent_message`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowAgentMessageCreate {
  project: number;
  channel: number;
  task?: number | null;
  sender_kind?: TaskflowAgentMessageSenderKind;
  sender_user?: number | null;
  sender_agent?: number | null;
  sender_label: string;
  body_markdown: string;
  priority?: TaskflowAgentMessagePriority;
  client_nonce?: string | null;
}
/** Body for updating a `taskflow_agent_message` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowAgentMessageUpdate {
  project?: number;
  channel?: number;
  task?: number | null;
  sender_kind?: TaskflowAgentMessageSenderKind;
  sender_user?: number | null;
  sender_agent?: number | null;
  sender_label?: string;
  body_markdown?: string;
  priority?: TaskflowAgentMessagePriority;
  client_nonce?: string | null;
}

/** Filterable query parameters for `taskflow_agent_session`. Every key is optional and AND-combined server-side. */
export interface TaskflowAgentSessionFilters {
  "project"?: number;
  "project__ne"?: number;
  "project__in"?: number[];
  "agent"?: number;
  "agent__ne"?: number;
  "agent__in"?: number[];
  "connected_by"?: number;
  "connected_by__ne"?: number;
  "connected_by__in"?: number[];
  "connected_by__isnull"?: boolean;
  "session_identifier"?: string;
  "session_identifier__ne"?: string;
  "session_identifier__contains"?: string;
  "session_identifier__icontains"?: string;
  "session_identifier__startswith"?: string;
  "session_identifier__in"?: string[];
  "host"?: string;
  "host__ne"?: string;
  "host__contains"?: string;
  "host__icontains"?: string;
  "host__startswith"?: string;
  "host__in"?: string[];
  "host__isnull"?: boolean;
  "pid"?: number;
  "pid__ne"?: number;
  "pid__gte"?: number;
  "pid__lte"?: number;
  "pid__gt"?: number;
  "pid__lt"?: number;
  "pid__in"?: number[];
  "pid__isnull"?: boolean;
  "cwd"?: string;
  "cwd__ne"?: string;
  "cwd__contains"?: string;
  "cwd__icontains"?: string;
  "cwd__startswith"?: string;
  "cwd__in"?: string[];
  "cwd__isnull"?: boolean;
  "transport"?: string;
  "transport__ne"?: string;
  "transport__contains"?: string;
  "transport__icontains"?: string;
  "transport__startswith"?: string;
  "transport__in"?: string[];
  "transport__isnull"?: boolean;
  "status"?: TaskflowAgentSessionStatus;
  "status__ne"?: TaskflowAgentSessionStatus;
  "status__contains"?: string;
  "status__icontains"?: string;
  "status__startswith"?: string;
  "status__in"?: TaskflowAgentSessionStatus[];
  "connected_at"?: string;
  "connected_at__ne"?: string;
  "connected_at__gte"?: string;
  "connected_at__lte"?: string;
  "connected_at__gt"?: string;
  "connected_at__lt"?: string;
  "connected_at__in"?: string[];
  "last_seen_at"?: string;
  "last_seen_at__ne"?: string;
  "last_seen_at__gte"?: string;
  "last_seen_at__lte"?: string;
  "last_seen_at__gt"?: string;
  "last_seen_at__lt"?: string;
  "last_seen_at__in"?: string[];
  "last_seen_at__isnull"?: boolean;
  "disconnected_at"?: string;
  "disconnected_at__ne"?: string;
  "disconnected_at__gte"?: string;
  "disconnected_at__lte"?: string;
  "disconnected_at__gt"?: string;
  "disconnected_at__lt"?: string;
  "disconnected_at__in"?: string[];
  "disconnected_at__isnull"?: boolean;
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
}
export type TaskflowAgentSessionOrdering = "id" | "-id" | "project" | "-project" | "agent" | "-agent" | "connected_by" | "-connected_by" | "session_identifier" | "-session_identifier" | "host" | "-host" | "pid" | "-pid" | "cwd" | "-cwd" | "transport" | "-transport" | "status" | "-status" | "connected_at" | "-connected_at" | "last_seen_at" | "-last_seen_at" | "disconnected_at" | "-disconnected_at" | "created_at" | "-created_at";
/** Body for creating a `taskflow_agent_session`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowAgentSessionCreate {
  project: number;
  agent: number;
  connected_by?: number | null;
  session_identifier: string;
  host?: string | null;
  pid?: number | null;
  cwd?: string | null;
  transport?: string | null;
  status?: TaskflowAgentSessionStatus;
  connected_at: string;
  last_seen_at?: string | null;
  disconnected_at?: string | null;
}
/** Body for updating a `taskflow_agent_session` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowAgentSessionUpdate {
  project?: number;
  agent?: number;
  connected_by?: number | null;
  session_identifier?: string;
  host?: string | null;
  pid?: number | null;
  cwd?: string | null;
  transport?: string | null;
  status?: TaskflowAgentSessionStatus;
  connected_at?: string;
  last_seen_at?: string | null;
  disconnected_at?: string | null;
}

/** Filterable query parameters for `taskflow_agent_terminal_frame`. Every key is optional and AND-combined server-side. */
export interface TaskflowAgentTerminalFrameFilters {
  "project"?: number;
  "project__ne"?: number;
  "project__in"?: number[];
  "agent"?: number;
  "agent__ne"?: number;
  "agent__in"?: number[];
  "session"?: number;
  "session__ne"?: number;
  "session__in"?: number[];
  "session__isnull"?: boolean;
  "task"?: number;
  "task__ne"?: number;
  "task__in"?: number[];
  "task__isnull"?: boolean;
  "stream"?: TaskflowAgentTerminalFrameStream;
  "stream__ne"?: TaskflowAgentTerminalFrameStream;
  "stream__contains"?: string;
  "stream__icontains"?: string;
  "stream__startswith"?: string;
  "stream__in"?: TaskflowAgentTerminalFrameStream[];
  "sequence"?: number;
  "sequence__ne"?: number;
  "sequence__gte"?: number;
  "sequence__lte"?: number;
  "sequence__gt"?: number;
  "sequence__lt"?: number;
  "sequence__in"?: number[];
  "content"?: string;
  "content__ne"?: string;
  "content__contains"?: string;
  "content__icontains"?: string;
  "content__startswith"?: string;
  "content__in"?: string[];
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
}
export type TaskflowAgentTerminalFrameOrdering = "id" | "-id" | "project" | "-project" | "agent" | "-agent" | "session" | "-session" | "task" | "-task" | "stream" | "-stream" | "sequence" | "-sequence" | "content" | "-content" | "created_at" | "-created_at";
/** Body for creating a `taskflow_agent_terminal_frame`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowAgentTerminalFrameCreate {
  project: number;
  agent: number;
  session?: number | null;
  task?: number | null;
  stream?: TaskflowAgentTerminalFrameStream;
  sequence?: number;
  content: string;
}
/** Body for updating a `taskflow_agent_terminal_frame` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowAgentTerminalFrameUpdate {
  project?: number;
  agent?: number;
  session?: number | null;
  task?: number | null;
  stream?: TaskflowAgentTerminalFrameStream;
  sequence?: number;
  content?: string;
}

/** Filterable query parameters for `taskflow_channel_read_cursor`. Every key is optional and AND-combined server-side. */
export interface TaskflowChannelReadCursorFilters {
  "project"?: number;
  "project__ne"?: number;
  "project__in"?: number[];
  "channel"?: number;
  "channel__ne"?: number;
  "channel__in"?: number[];
  "member_kind"?: TaskflowChannelReadCursorMemberKind;
  "member_kind__ne"?: TaskflowChannelReadCursorMemberKind;
  "member_kind__contains"?: string;
  "member_kind__icontains"?: string;
  "member_kind__startswith"?: string;
  "member_kind__in"?: TaskflowChannelReadCursorMemberKind[];
  "member_user"?: number;
  "member_user__ne"?: number;
  "member_user__in"?: number[];
  "member_user__isnull"?: boolean;
  "member_agent"?: number;
  "member_agent__ne"?: number;
  "member_agent__in"?: number[];
  "member_agent__isnull"?: boolean;
  "last_read_message"?: number;
  "last_read_message__ne"?: number;
  "last_read_message__in"?: number[];
  "last_read_message__isnull"?: boolean;
  "last_read_at"?: string;
  "last_read_at__ne"?: string;
  "last_read_at__gte"?: string;
  "last_read_at__lte"?: string;
  "last_read_at__gt"?: string;
  "last_read_at__lt"?: string;
  "last_read_at__in"?: string[];
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
}
export type TaskflowChannelReadCursorOrdering = "id" | "-id" | "project" | "-project" | "channel" | "-channel" | "member_kind" | "-member_kind" | "member_user" | "-member_user" | "member_agent" | "-member_agent" | "last_read_message" | "-last_read_message" | "last_read_at" | "-last_read_at" | "created_at" | "-created_at";
/** Body for creating a `taskflow_channel_read_cursor`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowChannelReadCursorCreate {
  project: number;
  channel: number;
  member_kind?: TaskflowChannelReadCursorMemberKind;
  member_user?: number | null;
  member_agent?: number | null;
  last_read_message?: number | null;
  last_read_at: string;
}
/** Body for updating a `taskflow_channel_read_cursor` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowChannelReadCursorUpdate {
  project?: number;
  channel?: number;
  member_kind?: TaskflowChannelReadCursorMemberKind;
  member_user?: number | null;
  member_agent?: number | null;
  last_read_message?: number | null;
  last_read_at?: string;
}

/** Filterable query parameters for `taskflow_message_attachment`. Every key is optional and AND-combined server-side. */
export interface TaskflowMessageAttachmentFilters {
  "message"?: number;
  "message__ne"?: number;
  "message__in"?: number[];
  "project"?: number;
  "project__ne"?: number;
  "project__in"?: number[];
  "file"?: string;
  "file__ne"?: string;
  "file__contains"?: string;
  "file__icontains"?: string;
  "file__startswith"?: string;
  "file__in"?: string[];
  "name"?: string;
  "name__ne"?: string;
  "name__contains"?: string;
  "name__icontains"?: string;
  "name__startswith"?: string;
  "name__in"?: string[];
  "content_type"?: string;
  "content_type__ne"?: string;
  "content_type__contains"?: string;
  "content_type__icontains"?: string;
  "content_type__startswith"?: string;
  "content_type__in"?: string[];
  "size_bytes"?: number;
  "size_bytes__ne"?: number;
  "size_bytes__gte"?: number;
  "size_bytes__lte"?: number;
  "size_bytes__gt"?: number;
  "size_bytes__lt"?: number;
  "size_bytes__in"?: number[];
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
}
export type TaskflowMessageAttachmentOrdering = "id" | "-id" | "message" | "-message" | "project" | "-project" | "file" | "-file" | "name" | "-name" | "content_type" | "-content_type" | "size_bytes" | "-size_bytes" | "created_at" | "-created_at";
/** Body for creating a `taskflow_message_attachment`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowMessageAttachmentCreate {
  message: number;
  project: number;
  file: string;
  name: string;
  content_type: string;
  size_bytes: number;
}
/** Body for updating a `taskflow_message_attachment` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowMessageAttachmentUpdate {
  message?: number;
  project?: number;
  file?: string;
  name?: string;
  content_type?: string;
  size_bytes?: number;
}

/** Filterable query parameters for `taskflow_project`. Every key is optional and AND-combined server-side. */
export interface TaskflowProjectFilters {
  "name"?: string;
  "name__ne"?: string;
  "name__contains"?: string;
  "name__icontains"?: string;
  "name__startswith"?: string;
  "name__in"?: string[];
  "slug"?: string;
  "slug__ne"?: string;
  "slug__contains"?: string;
  "slug__icontains"?: string;
  "slug__startswith"?: string;
  "slug__in"?: string[];
  "description_markdown"?: string;
  "description_markdown__ne"?: string;
  "description_markdown__contains"?: string;
  "description_markdown__icontains"?: string;
  "description_markdown__startswith"?: string;
  "description_markdown__in"?: string[];
  "repository_url"?: string;
  "repository_url__ne"?: string;
  "repository_url__contains"?: string;
  "repository_url__icontains"?: string;
  "repository_url__startswith"?: string;
  "repository_url__in"?: string[];
  "repository_url__isnull"?: boolean;
  "default_api_base_url"?: string;
  "default_api_base_url__ne"?: string;
  "default_api_base_url__contains"?: string;
  "default_api_base_url__icontains"?: string;
  "default_api_base_url__startswith"?: string;
  "default_api_base_url__in"?: string[];
  "default_api_base_url__isnull"?: boolean;
  "status"?: TaskflowProjectStatus;
  "status__ne"?: TaskflowProjectStatus;
  "status__contains"?: string;
  "status__icontains"?: string;
  "status__startswith"?: string;
  "status__in"?: TaskflowProjectStatus[];
  "owner"?: number;
  "owner__ne"?: number;
  "owner__in"?: number[];
  "owner__isnull"?: boolean;
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
  "updated_at"?: string;
  "updated_at__ne"?: string;
  "updated_at__gte"?: string;
  "updated_at__lte"?: string;
  "updated_at__gt"?: string;
  "updated_at__lt"?: string;
  "updated_at__in"?: string[];
  "updated_at__isnull"?: boolean;
}
export type TaskflowProjectOrdering = "id" | "-id" | "name" | "-name" | "slug" | "-slug" | "description_markdown" | "-description_markdown" | "repository_url" | "-repository_url" | "default_api_base_url" | "-default_api_base_url" | "status" | "-status" | "owner" | "-owner" | "created_at" | "-created_at" | "updated_at" | "-updated_at";
/** Body for creating a `taskflow_project`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowProjectCreate {
  name: string;
  slug: string;
  description_markdown: string;
  repository_url?: string | null;
  default_api_base_url?: string | null;
  status?: TaskflowProjectStatus;
  owner?: number | null;
  updated_at?: string | null;
}
/** Body for updating a `taskflow_project` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowProjectUpdate {
  name?: string;
  slug?: string;
  description_markdown?: string;
  repository_url?: string | null;
  default_api_base_url?: string | null;
  status?: TaskflowProjectStatus;
  owner?: number | null;
}

/** Filterable query parameters for `taskflow_project_api_endpoint`. Every key is optional and AND-combined server-side. */
export interface TaskflowProjectApiEndpointFilters {
  "project"?: number;
  "project__ne"?: number;
  "project__in"?: number[];
  "label"?: string;
  "label__ne"?: string;
  "label__contains"?: string;
  "label__icontains"?: string;
  "label__startswith"?: string;
  "label__in"?: string[];
  "base_url"?: string;
  "base_url__ne"?: string;
  "base_url__contains"?: string;
  "base_url__icontains"?: string;
  "base_url__startswith"?: string;
  "base_url__in"?: string[];
  "environment"?: TaskflowProjectApiEndpointEnvironment;
  "environment__ne"?: TaskflowProjectApiEndpointEnvironment;
  "environment__contains"?: string;
  "environment__icontains"?: string;
  "environment__startswith"?: string;
  "environment__in"?: TaskflowProjectApiEndpointEnvironment[];
  "health"?: TaskflowProjectApiEndpointHealth;
  "health__ne"?: TaskflowProjectApiEndpointHealth;
  "health__contains"?: string;
  "health__icontains"?: string;
  "health__startswith"?: string;
  "health__in"?: TaskflowProjectApiEndpointHealth[];
  "is_default"?: boolean;
  "is_default__ne"?: boolean;
  "is_default__in"?: boolean[];
  "notes_markdown"?: string;
  "notes_markdown__ne"?: string;
  "notes_markdown__contains"?: string;
  "notes_markdown__icontains"?: string;
  "notes_markdown__startswith"?: string;
  "notes_markdown__in"?: string[];
  "notes_markdown__isnull"?: boolean;
  "last_checked_at"?: string;
  "last_checked_at__ne"?: string;
  "last_checked_at__gte"?: string;
  "last_checked_at__lte"?: string;
  "last_checked_at__gt"?: string;
  "last_checked_at__lt"?: string;
  "last_checked_at__in"?: string[];
  "last_checked_at__isnull"?: boolean;
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
}
export type TaskflowProjectApiEndpointOrdering = "id" | "-id" | "project" | "-project" | "label" | "-label" | "base_url" | "-base_url" | "environment" | "-environment" | "health" | "-health" | "is_default" | "-is_default" | "notes_markdown" | "-notes_markdown" | "last_checked_at" | "-last_checked_at" | "created_at" | "-created_at";
/** Body for creating a `taskflow_project_api_endpoint`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowProjectApiEndpointCreate {
  project: number;
  label: string;
  base_url: string;
  environment?: TaskflowProjectApiEndpointEnvironment;
  health?: TaskflowProjectApiEndpointHealth;
  is_default?: boolean;
  notes_markdown?: string | null;
  last_checked_at?: string | null;
}
/** Body for updating a `taskflow_project_api_endpoint` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowProjectApiEndpointUpdate {
  project?: number;
  label?: string;
  base_url?: string;
  environment?: TaskflowProjectApiEndpointEnvironment;
  health?: TaskflowProjectApiEndpointHealth;
  is_default?: boolean;
  notes_markdown?: string | null;
  last_checked_at?: string | null;
}

/** Filterable query parameters for `taskflow_project_invite`. Every key is optional and AND-combined server-side. */
export interface TaskflowProjectInviteFilters {
  "project"?: number;
  "project__ne"?: number;
  "project__in"?: number[];
  "email"?: string;
  "email__ne"?: string;
  "email__contains"?: string;
  "email__icontains"?: string;
  "email__startswith"?: string;
  "email__in"?: string[];
  "display_name"?: string;
  "display_name__ne"?: string;
  "display_name__contains"?: string;
  "display_name__icontains"?: string;
  "display_name__startswith"?: string;
  "display_name__in"?: string[];
  "display_name__isnull"?: boolean;
  "role"?: TaskflowProjectInviteRole;
  "role__ne"?: TaskflowProjectInviteRole;
  "role__contains"?: string;
  "role__icontains"?: string;
  "role__startswith"?: string;
  "role__in"?: TaskflowProjectInviteRole[];
  "status"?: TaskflowProjectInviteStatus;
  "status__ne"?: TaskflowProjectInviteStatus;
  "status__contains"?: string;
  "status__icontains"?: string;
  "status__startswith"?: string;
  "status__in"?: TaskflowProjectInviteStatus[];
  "invite_token"?: string;
  "invite_token__ne"?: string;
  "invite_token__contains"?: string;
  "invite_token__icontains"?: string;
  "invite_token__startswith"?: string;
  "invite_token__in"?: string[];
  "invited_by"?: number;
  "invited_by__ne"?: number;
  "invited_by__in"?: number[];
  "invited_by__isnull"?: boolean;
  "expires_at"?: string;
  "expires_at__ne"?: string;
  "expires_at__gte"?: string;
  "expires_at__lte"?: string;
  "expires_at__gt"?: string;
  "expires_at__lt"?: string;
  "expires_at__in"?: string[];
  "expires_at__isnull"?: boolean;
  "accepted_at"?: string;
  "accepted_at__ne"?: string;
  "accepted_at__gte"?: string;
  "accepted_at__lte"?: string;
  "accepted_at__gt"?: string;
  "accepted_at__lt"?: string;
  "accepted_at__in"?: string[];
  "accepted_at__isnull"?: boolean;
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
}
export type TaskflowProjectInviteOrdering = "id" | "-id" | "project" | "-project" | "email" | "-email" | "display_name" | "-display_name" | "role" | "-role" | "status" | "-status" | "invite_token" | "-invite_token" | "invited_by" | "-invited_by" | "expires_at" | "-expires_at" | "accepted_at" | "-accepted_at" | "created_at" | "-created_at";
/** Body for creating a `taskflow_project_invite`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowProjectInviteCreate {
  project: number;
  email: string;
  display_name?: string | null;
  role?: TaskflowProjectInviteRole;
  status?: TaskflowProjectInviteStatus;
  invite_token: string;
  invited_by?: number | null;
  expires_at?: string | null;
  accepted_at?: string | null;
}
/** Body for updating a `taskflow_project_invite` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowProjectInviteUpdate {
  project?: number;
  email?: string;
  display_name?: string | null;
  role?: TaskflowProjectInviteRole;
  status?: TaskflowProjectInviteStatus;
  invite_token?: string;
  invited_by?: number | null;
  expires_at?: string | null;
  accepted_at?: string | null;
}

/** Filterable query parameters for `taskflow_project_member`. Every key is optional and AND-combined server-side. */
export interface TaskflowProjectMemberFilters {
  "project"?: number;
  "project__ne"?: number;
  "project__in"?: number[];
  "member_key"?: string;
  "member_key__ne"?: string;
  "member_key__contains"?: string;
  "member_key__icontains"?: string;
  "member_key__startswith"?: string;
  "member_key__in"?: string[];
  "user"?: number;
  "user__ne"?: number;
  "user__in"?: number[];
  "user__isnull"?: boolean;
  "display_name"?: string;
  "display_name__ne"?: string;
  "display_name__contains"?: string;
  "display_name__icontains"?: string;
  "display_name__startswith"?: string;
  "display_name__in"?: string[];
  "email"?: string;
  "email__ne"?: string;
  "email__contains"?: string;
  "email__icontains"?: string;
  "email__startswith"?: string;
  "email__in"?: string[];
  "email__isnull"?: boolean;
  "role"?: TaskflowProjectMemberRole;
  "role__ne"?: TaskflowProjectMemberRole;
  "role__contains"?: string;
  "role__icontains"?: string;
  "role__startswith"?: string;
  "role__in"?: TaskflowProjectMemberRole[];
  "status"?: TaskflowProjectMemberStatus;
  "status__ne"?: TaskflowProjectMemberStatus;
  "status__contains"?: string;
  "status__icontains"?: string;
  "status__startswith"?: string;
  "status__in"?: TaskflowProjectMemberStatus[];
  "invited_by"?: number;
  "invited_by__ne"?: number;
  "invited_by__in"?: number[];
  "invited_by__isnull"?: boolean;
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
  "joined_at"?: string;
  "joined_at__ne"?: string;
  "joined_at__gte"?: string;
  "joined_at__lte"?: string;
  "joined_at__gt"?: string;
  "joined_at__lt"?: string;
  "joined_at__in"?: string[];
  "joined_at__isnull"?: boolean;
}
export type TaskflowProjectMemberOrdering = "id" | "-id" | "project" | "-project" | "member_key" | "-member_key" | "user" | "-user" | "display_name" | "-display_name" | "email" | "-email" | "role" | "-role" | "status" | "-status" | "invited_by" | "-invited_by" | "created_at" | "-created_at" | "joined_at" | "-joined_at";
/** Body for creating a `taskflow_project_member`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowProjectMemberCreate {
  project: number;
  member_key: string;
  user?: number | null;
  display_name: string;
  email?: string | null;
  role?: TaskflowProjectMemberRole;
  status?: TaskflowProjectMemberStatus;
  invited_by?: number | null;
  joined_at?: string | null;
}
/** Body for updating a `taskflow_project_member` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowProjectMemberUpdate {
  project?: number;
  member_key?: string;
  user?: number | null;
  display_name?: string;
  email?: string | null;
  role?: TaskflowProjectMemberRole;
  status?: TaskflowProjectMemberStatus;
  invited_by?: number | null;
}

/** Filterable query parameters for `taskflow_task`. Every key is optional and AND-combined server-side. */
export interface TaskflowTaskFilters {
  "project"?: number;
  "project__ne"?: number;
  "project__in"?: number[];
  "title"?: string;
  "title__ne"?: string;
  "title__contains"?: string;
  "title__icontains"?: string;
  "title__startswith"?: string;
  "title__in"?: string[];
  "description_markdown"?: string;
  "description_markdown__ne"?: string;
  "description_markdown__contains"?: string;
  "description_markdown__icontains"?: string;
  "description_markdown__startswith"?: string;
  "description_markdown__in"?: string[];
  "notes_markdown"?: string;
  "notes_markdown__ne"?: string;
  "notes_markdown__contains"?: string;
  "notes_markdown__icontains"?: string;
  "notes_markdown__startswith"?: string;
  "notes_markdown__in"?: string[];
  "notes_markdown__isnull"?: boolean;
  "status"?: TaskflowTaskStatus;
  "status__ne"?: TaskflowTaskStatus;
  "status__contains"?: string;
  "status__icontains"?: string;
  "status__startswith"?: string;
  "status__in"?: TaskflowTaskStatus[];
  "priority"?: TaskflowTaskPriority;
  "priority__ne"?: TaskflowTaskPriority;
  "priority__contains"?: string;
  "priority__icontains"?: string;
  "priority__startswith"?: string;
  "priority__in"?: TaskflowTaskPriority[];
  "sort_order"?: number;
  "sort_order__ne"?: number;
  "sort_order__gte"?: number;
  "sort_order__lte"?: number;
  "sort_order__gt"?: number;
  "sort_order__lt"?: number;
  "sort_order__in"?: number[];
  "created_by"?: number;
  "created_by__ne"?: number;
  "created_by__in"?: number[];
  "created_by__isnull"?: boolean;
  "assigned_user"?: number;
  "assigned_user__ne"?: number;
  "assigned_user__in"?: number[];
  "assigned_user__isnull"?: boolean;
  "assigned_agent_id"?: number;
  "assigned_agent_id__ne"?: number;
  "assigned_agent_id__gte"?: number;
  "assigned_agent_id__lte"?: number;
  "assigned_agent_id__gt"?: number;
  "assigned_agent_id__lt"?: number;
  "assigned_agent_id__in"?: number[];
  "assigned_agent_id__isnull"?: boolean;
  "assignee_label"?: string;
  "assignee_label__ne"?: string;
  "assignee_label__contains"?: string;
  "assignee_label__icontains"?: string;
  "assignee_label__startswith"?: string;
  "assignee_label__in"?: string[];
  "assignee_label__isnull"?: boolean;
  "due_at"?: string;
  "due_at__ne"?: string;
  "due_at__gte"?: string;
  "due_at__lte"?: string;
  "due_at__gt"?: string;
  "due_at__lt"?: string;
  "due_at__in"?: string[];
  "due_at__isnull"?: boolean;
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
  "updated_at"?: string;
  "updated_at__ne"?: string;
  "updated_at__gte"?: string;
  "updated_at__lte"?: string;
  "updated_at__gt"?: string;
  "updated_at__lt"?: string;
  "updated_at__in"?: string[];
  "updated_at__isnull"?: boolean;
}
export type TaskflowTaskOrdering = "id" | "-id" | "project" | "-project" | "title" | "-title" | "description_markdown" | "-description_markdown" | "notes_markdown" | "-notes_markdown" | "status" | "-status" | "priority" | "-priority" | "sort_order" | "-sort_order" | "created_by" | "-created_by" | "assigned_user" | "-assigned_user" | "assigned_agent_id" | "-assigned_agent_id" | "assignee_label" | "-assignee_label" | "due_at" | "-due_at" | "created_at" | "-created_at" | "updated_at" | "-updated_at";
/** Body for creating a `taskflow_task`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowTaskCreate {
  project: number;
  title: string;
  description_markdown: string;
  notes_markdown?: string | null;
  status?: TaskflowTaskStatus;
  priority?: TaskflowTaskPriority;
  sort_order?: number;
  created_by?: number | null;
  assigned_user?: number | null;
  assigned_agent_id?: number | null;
  assignee_label?: string | null;
  due_at?: string | null;
  updated_at?: string | null;
}
/** Body for updating a `taskflow_task` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowTaskUpdate {
  project?: number;
  title?: string;
  description_markdown?: string;
  notes_markdown?: string | null;
  status?: TaskflowTaskStatus;
  priority?: TaskflowTaskPriority;
  sort_order?: number;
  created_by?: number | null;
  assigned_user?: number | null;
  assigned_agent_id?: number | null;
  assignee_label?: string | null;
  due_at?: string | null;
}

/** Filterable query parameters for `taskflow_task_activity`. Every key is optional and AND-combined server-side. */
export interface TaskflowTaskActivityFilters {
  "project"?: number;
  "project__ne"?: number;
  "project__in"?: number[];
  "task"?: number;
  "task__ne"?: number;
  "task__in"?: number[];
  "task__isnull"?: boolean;
  "actor_kind"?: TaskflowTaskActivityActorKind;
  "actor_kind__ne"?: TaskflowTaskActivityActorKind;
  "actor_kind__contains"?: string;
  "actor_kind__icontains"?: string;
  "actor_kind__startswith"?: string;
  "actor_kind__in"?: TaskflowTaskActivityActorKind[];
  "actor_user"?: number;
  "actor_user__ne"?: number;
  "actor_user__in"?: number[];
  "actor_user__isnull"?: boolean;
  "actor_agent_id"?: number;
  "actor_agent_id__ne"?: number;
  "actor_agent_id__gte"?: number;
  "actor_agent_id__lte"?: number;
  "actor_agent_id__gt"?: number;
  "actor_agent_id__lt"?: number;
  "actor_agent_id__in"?: number[];
  "actor_agent_id__isnull"?: boolean;
  "actor_label"?: string;
  "actor_label__ne"?: string;
  "actor_label__contains"?: string;
  "actor_label__icontains"?: string;
  "actor_label__startswith"?: string;
  "actor_label__in"?: string[];
  "action"?: string;
  "action__ne"?: string;
  "action__contains"?: string;
  "action__icontains"?: string;
  "action__startswith"?: string;
  "action__in"?: string[];
  "body_markdown"?: string;
  "body_markdown__ne"?: string;
  "body_markdown__contains"?: string;
  "body_markdown__icontains"?: string;
  "body_markdown__startswith"?: string;
  "body_markdown__in"?: string[];
  "body_markdown__isnull"?: boolean;
  "metadata_json"?: string;
  "metadata_json__ne"?: string;
  "metadata_json__contains"?: string;
  "metadata_json__icontains"?: string;
  "metadata_json__startswith"?: string;
  "metadata_json__in"?: string[];
  "metadata_json__isnull"?: boolean;
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
}
export type TaskflowTaskActivityOrdering = "id" | "-id" | "project" | "-project" | "task" | "-task" | "actor_kind" | "-actor_kind" | "actor_user" | "-actor_user" | "actor_agent_id" | "-actor_agent_id" | "actor_label" | "-actor_label" | "action" | "-action" | "body_markdown" | "-body_markdown" | "metadata_json" | "-metadata_json" | "created_at" | "-created_at";
/** Body for creating a `taskflow_task_activity`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowTaskActivityCreate {
  project: number;
  task?: number | null;
  actor_kind?: TaskflowTaskActivityActorKind;
  actor_user?: number | null;
  actor_agent_id?: number | null;
  actor_label: string;
  action: string;
  body_markdown?: string | null;
  metadata_json?: string | null;
}
/** Body for updating a `taskflow_task_activity` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowTaskActivityUpdate {
  project?: number;
  task?: number | null;
  actor_kind?: TaskflowTaskActivityActorKind;
  actor_user?: number | null;
  actor_agent_id?: number | null;
  actor_label?: string;
  action?: string;
  body_markdown?: string | null;
  metadata_json?: string | null;
}

/** Filterable query parameters for `taskflow_task_relation`. Every key is optional and AND-combined server-side. */
export interface TaskflowTaskRelationFilters {
  "project"?: number;
  "project__ne"?: number;
  "project__in"?: number[];
  "source_task"?: number;
  "source_task__ne"?: number;
  "source_task__in"?: number[];
  "target_task"?: number;
  "target_task__ne"?: number;
  "target_task__in"?: number[];
  "kind"?: TaskflowTaskRelationKind;
  "kind__ne"?: TaskflowTaskRelationKind;
  "kind__contains"?: string;
  "kind__icontains"?: string;
  "kind__startswith"?: string;
  "kind__in"?: TaskflowTaskRelationKind[];
  "detail_markdown"?: string;
  "detail_markdown__ne"?: string;
  "detail_markdown__contains"?: string;
  "detail_markdown__icontains"?: string;
  "detail_markdown__startswith"?: string;
  "detail_markdown__in"?: string[];
  "detail_markdown__isnull"?: boolean;
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
}
export type TaskflowTaskRelationOrdering = "id" | "-id" | "project" | "-project" | "source_task" | "-source_task" | "target_task" | "-target_task" | "kind" | "-kind" | "detail_markdown" | "-detail_markdown" | "created_at" | "-created_at";
/** Body for creating a `taskflow_task_relation`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowTaskRelationCreate {
  project: number;
  source_task: number;
  target_task: number;
  kind?: TaskflowTaskRelationKind;
  detail_markdown?: string | null;
}
/** Body for updating a `taskflow_task_relation` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowTaskRelationUpdate {
  project?: number;
  source_task?: number;
  target_task?: number;
  kind?: TaskflowTaskRelationKind;
  detail_markdown?: string | null;
}

/** Filterable query parameters for `taskflow_task_review`. Every key is optional and AND-combined server-side. */
export interface TaskflowTaskReviewFilters {
  "project"?: number;
  "project__ne"?: number;
  "project__in"?: number[];
  "task"?: number;
  "task__ne"?: number;
  "task__in"?: number[];
  "reviewer_kind"?: TaskflowTaskReviewReviewerKind;
  "reviewer_kind__ne"?: TaskflowTaskReviewReviewerKind;
  "reviewer_kind__contains"?: string;
  "reviewer_kind__icontains"?: string;
  "reviewer_kind__startswith"?: string;
  "reviewer_kind__in"?: TaskflowTaskReviewReviewerKind[];
  "reviewer_user"?: number;
  "reviewer_user__ne"?: number;
  "reviewer_user__in"?: number[];
  "reviewer_user__isnull"?: boolean;
  "reviewer_agent"?: number;
  "reviewer_agent__ne"?: number;
  "reviewer_agent__in"?: number[];
  "reviewer_agent__isnull"?: boolean;
  "reviewer_label"?: string;
  "reviewer_label__ne"?: string;
  "reviewer_label__contains"?: string;
  "reviewer_label__icontains"?: string;
  "reviewer_label__startswith"?: string;
  "reviewer_label__in"?: string[];
  "decision"?: TaskflowTaskReviewDecision;
  "decision__ne"?: TaskflowTaskReviewDecision;
  "decision__contains"?: string;
  "decision__icontains"?: string;
  "decision__startswith"?: string;
  "decision__in"?: TaskflowTaskReviewDecision[];
  "body_markdown"?: string;
  "body_markdown__ne"?: string;
  "body_markdown__contains"?: string;
  "body_markdown__icontains"?: string;
  "body_markdown__startswith"?: string;
  "body_markdown__in"?: string[];
  "body_markdown__isnull"?: boolean;
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
}
export type TaskflowTaskReviewOrdering = "id" | "-id" | "project" | "-project" | "task" | "-task" | "reviewer_kind" | "-reviewer_kind" | "reviewer_user" | "-reviewer_user" | "reviewer_agent" | "-reviewer_agent" | "reviewer_label" | "-reviewer_label" | "decision" | "-decision" | "body_markdown" | "-body_markdown" | "created_at" | "-created_at";
/** Body for creating a `taskflow_task_review`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowTaskReviewCreate {
  project: number;
  task: number;
  reviewer_kind?: TaskflowTaskReviewReviewerKind;
  reviewer_user?: number | null;
  reviewer_agent?: number | null;
  reviewer_label: string;
  decision?: TaskflowTaskReviewDecision;
  body_markdown?: string | null;
}
/** Body for updating a `taskflow_task_review` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowTaskReviewUpdate {
  project?: number;
  task?: number;
  reviewer_kind?: TaskflowTaskReviewReviewerKind;
  reviewer_user?: number | null;
  reviewer_agent?: number | null;
  reviewer_label?: string;
  decision?: TaskflowTaskReviewDecision;
  body_markdown?: string | null;
}

/** Filterable query parameters for `taskflow_task_session`. Every key is optional and AND-combined server-side. */
export interface TaskflowTaskSessionFilters {
  "project"?: number;
  "project__ne"?: number;
  "project__in"?: number[];
  "task"?: number;
  "task__ne"?: number;
  "task__in"?: number[];
  "state"?: TaskflowTaskSessionState;
  "state__ne"?: TaskflowTaskSessionState;
  "state__contains"?: string;
  "state__icontains"?: string;
  "state__startswith"?: string;
  "state__in"?: TaskflowTaskSessionState[];
  "actor_kind"?: TaskflowTaskSessionActorKind;
  "actor_kind__ne"?: TaskflowTaskSessionActorKind;
  "actor_kind__contains"?: string;
  "actor_kind__icontains"?: string;
  "actor_kind__startswith"?: string;
  "actor_kind__in"?: TaskflowTaskSessionActorKind[];
  "actor_user"?: number;
  "actor_user__ne"?: number;
  "actor_user__in"?: number[];
  "actor_user__isnull"?: boolean;
  "actor_agent_id"?: number;
  "actor_agent_id__ne"?: number;
  "actor_agent_id__gte"?: number;
  "actor_agent_id__lte"?: number;
  "actor_agent_id__gt"?: number;
  "actor_agent_id__lt"?: number;
  "actor_agent_id__in"?: number[];
  "actor_agent_id__isnull"?: boolean;
  "actor_label"?: string;
  "actor_label__ne"?: string;
  "actor_label__contains"?: string;
  "actor_label__icontains"?: string;
  "actor_label__startswith"?: string;
  "actor_label__in"?: string[];
  "started_at"?: string;
  "started_at__ne"?: string;
  "started_at__gte"?: string;
  "started_at__lte"?: string;
  "started_at__gt"?: string;
  "started_at__lt"?: string;
  "started_at__in"?: string[];
  "ended_at"?: string;
  "ended_at__ne"?: string;
  "ended_at__gte"?: string;
  "ended_at__lte"?: string;
  "ended_at__gt"?: string;
  "ended_at__lt"?: string;
  "ended_at__in"?: string[];
  "ended_at__isnull"?: boolean;
  "duration_seconds"?: number;
  "duration_seconds__ne"?: number;
  "duration_seconds__gte"?: number;
  "duration_seconds__lte"?: number;
  "duration_seconds__gt"?: number;
  "duration_seconds__lt"?: number;
  "duration_seconds__in"?: number[];
  "duration_seconds__isnull"?: boolean;
  "summary_markdown"?: string;
  "summary_markdown__ne"?: string;
  "summary_markdown__contains"?: string;
  "summary_markdown__icontains"?: string;
  "summary_markdown__startswith"?: string;
  "summary_markdown__in"?: string[];
  "summary_markdown__isnull"?: boolean;
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
}
export type TaskflowTaskSessionOrdering = "id" | "-id" | "project" | "-project" | "task" | "-task" | "state" | "-state" | "actor_kind" | "-actor_kind" | "actor_user" | "-actor_user" | "actor_agent_id" | "-actor_agent_id" | "actor_label" | "-actor_label" | "started_at" | "-started_at" | "ended_at" | "-ended_at" | "duration_seconds" | "-duration_seconds" | "summary_markdown" | "-summary_markdown" | "created_at" | "-created_at";
/** Body for creating a `taskflow_task_session`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowTaskSessionCreate {
  project: number;
  task: number;
  state?: TaskflowTaskSessionState;
  actor_kind?: TaskflowTaskSessionActorKind;
  actor_user?: number | null;
  actor_agent_id?: number | null;
  actor_label: string;
  started_at: string;
  ended_at?: string | null;
  duration_seconds?: number | null;
  summary_markdown?: string | null;
}
/** Body for updating a `taskflow_task_session` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowTaskSessionUpdate {
  project?: number;
  task?: number;
  state?: TaskflowTaskSessionState;
  actor_kind?: TaskflowTaskSessionActorKind;
  actor_user?: number | null;
  actor_agent_id?: number | null;
  actor_label?: string;
  started_at?: string;
  ended_at?: string | null;
  duration_seconds?: number | null;
  summary_markdown?: string | null;
}

/** Filterable query parameters for `taskflow_user_settings`. Every key is optional and AND-combined server-side. */
export interface TaskflowUserSettingsFilters {
  "user"?: number;
  "user__ne"?: number;
  "user__in"?: number[];
  "theme"?: TaskflowUserSettingsTheme;
  "theme__ne"?: TaskflowUserSettingsTheme;
  "theme__contains"?: string;
  "theme__icontains"?: string;
  "theme__startswith"?: string;
  "theme__in"?: TaskflowUserSettingsTheme[];
  "email_notifications"?: boolean;
  "email_notifications__ne"?: boolean;
  "email_notifications__in"?: boolean[];
  "default_project"?: number;
  "default_project__ne"?: number;
  "default_project__in"?: number[];
  "default_project__isnull"?: boolean;
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
  "created_at__isnull"?: boolean;
  "updated_at"?: string;
  "updated_at__ne"?: string;
  "updated_at__gte"?: string;
  "updated_at__lte"?: string;
  "updated_at__gt"?: string;
  "updated_at__lt"?: string;
  "updated_at__in"?: string[];
  "updated_at__isnull"?: boolean;
}
export type TaskflowUserSettingsOrdering = "id" | "-id" | "user" | "-user" | "theme" | "-theme" | "email_notifications" | "-email_notifications" | "default_project" | "-default_project" | "created_at" | "-created_at" | "updated_at" | "-updated_at";
/** Body for creating a `taskflow_user_settings`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface TaskflowUserSettingsCreate {
  user: number;
  theme?: TaskflowUserSettingsTheme;
  email_notifications?: boolean;
  default_project?: number | null;
  updated_at?: string | null;
}
/** Body for updating a `taskflow_user_settings` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface TaskflowUserSettingsUpdate {
  user?: number;
  theme?: TaskflowUserSettingsTheme;
  email_notifications?: boolean;
  default_project?: number | null;
}

/** A list response. `results` + `count` are always present; the rest depend on the paginator. */
export interface Paginated<T> {
  results: T[];
  count: number;
}

/** Maps each REST-exposed table to its row, filter, and ordering types. `Umbral.from` keys off this. */
export interface UmbralResources {
  "admin_user_pref": { row: AdminUserPref; filters: AdminUserPrefFilters; ordering: AdminUserPrefOrdering; create: AdminUserPrefCreate; update: AdminUserPrefUpdate; id: number };
  "auth_challenge": { row: AuthChallenge; filters: AuthChallengeFilters; ordering: AuthChallengeOrdering; create: AuthChallengeCreate; update: AuthChallengeUpdate; id: number };
  "auth_token": { row: AuthToken; filters: AuthTokenFilters; ordering: AuthTokenOrdering; create: AuthTokenCreate; update: AuthTokenUpdate; id: number };
  "media_file": { row: MediaFile; filters: MediaFileFilters; ordering: MediaFileOrdering; create: MediaFileCreate; update: MediaFileUpdate; id: number };
  "post": { row: Post; filters: PostFilters; ordering: PostOrdering; create: PostCreate; update: PostUpdate; id: number };
  "taskflow_agent": { row: TaskflowAgent; filters: TaskflowAgentFilters; ordering: TaskflowAgentOrdering; create: TaskflowAgentCreate; update: TaskflowAgentUpdate; id: number };
  "taskflow_agent_channel": { row: TaskflowAgentChannel; filters: TaskflowAgentChannelFilters; ordering: TaskflowAgentChannelOrdering; create: TaskflowAgentChannelCreate; update: TaskflowAgentChannelUpdate; id: number };
  "taskflow_agent_channel_member": { row: TaskflowAgentChannelMember; filters: TaskflowAgentChannelMemberFilters; ordering: TaskflowAgentChannelMemberOrdering; create: TaskflowAgentChannelMemberCreate; update: TaskflowAgentChannelMemberUpdate; id: number };
  "taskflow_agent_credential": { row: TaskflowAgentCredential; filters: TaskflowAgentCredentialFilters; ordering: TaskflowAgentCredentialOrdering; create: TaskflowAgentCredentialCreate; update: TaskflowAgentCredentialUpdate; id: number };
  "taskflow_agent_message": { row: TaskflowAgentMessage; filters: TaskflowAgentMessageFilters; ordering: TaskflowAgentMessageOrdering; create: TaskflowAgentMessageCreate; update: TaskflowAgentMessageUpdate; id: number };
  "taskflow_agent_session": { row: TaskflowAgentSession; filters: TaskflowAgentSessionFilters; ordering: TaskflowAgentSessionOrdering; create: TaskflowAgentSessionCreate; update: TaskflowAgentSessionUpdate; id: number };
  "taskflow_agent_terminal_frame": { row: TaskflowAgentTerminalFrame; filters: TaskflowAgentTerminalFrameFilters; ordering: TaskflowAgentTerminalFrameOrdering; create: TaskflowAgentTerminalFrameCreate; update: TaskflowAgentTerminalFrameUpdate; id: number };
  "taskflow_channel_read_cursor": { row: TaskflowChannelReadCursor; filters: TaskflowChannelReadCursorFilters; ordering: TaskflowChannelReadCursorOrdering; create: TaskflowChannelReadCursorCreate; update: TaskflowChannelReadCursorUpdate; id: number };
  "taskflow_message_attachment": { row: TaskflowMessageAttachment; filters: TaskflowMessageAttachmentFilters; ordering: TaskflowMessageAttachmentOrdering; create: TaskflowMessageAttachmentCreate; update: TaskflowMessageAttachmentUpdate; id: number };
  "taskflow_project": { row: TaskflowProject; filters: TaskflowProjectFilters; ordering: TaskflowProjectOrdering; create: TaskflowProjectCreate; update: TaskflowProjectUpdate; id: number };
  "taskflow_project_api_endpoint": { row: TaskflowProjectApiEndpoint; filters: TaskflowProjectApiEndpointFilters; ordering: TaskflowProjectApiEndpointOrdering; create: TaskflowProjectApiEndpointCreate; update: TaskflowProjectApiEndpointUpdate; id: number };
  "taskflow_project_invite": { row: TaskflowProjectInvite; filters: TaskflowProjectInviteFilters; ordering: TaskflowProjectInviteOrdering; create: TaskflowProjectInviteCreate; update: TaskflowProjectInviteUpdate; id: number };
  "taskflow_project_member": { row: TaskflowProjectMember; filters: TaskflowProjectMemberFilters; ordering: TaskflowProjectMemberOrdering; create: TaskflowProjectMemberCreate; update: TaskflowProjectMemberUpdate; id: number };
  "taskflow_task": { row: TaskflowTask; filters: TaskflowTaskFilters; ordering: TaskflowTaskOrdering; create: TaskflowTaskCreate; update: TaskflowTaskUpdate; id: number };
  "taskflow_task_activity": { row: TaskflowTaskActivity; filters: TaskflowTaskActivityFilters; ordering: TaskflowTaskActivityOrdering; create: TaskflowTaskActivityCreate; update: TaskflowTaskActivityUpdate; id: number };
  "taskflow_task_relation": { row: TaskflowTaskRelation; filters: TaskflowTaskRelationFilters; ordering: TaskflowTaskRelationOrdering; create: TaskflowTaskRelationCreate; update: TaskflowTaskRelationUpdate; id: number };
  "taskflow_task_review": { row: TaskflowTaskReview; filters: TaskflowTaskReviewFilters; ordering: TaskflowTaskReviewOrdering; create: TaskflowTaskReviewCreate; update: TaskflowTaskReviewUpdate; id: number };
  "taskflow_task_session": { row: TaskflowTaskSession; filters: TaskflowTaskSessionFilters; ordering: TaskflowTaskSessionOrdering; create: TaskflowTaskSessionCreate; update: TaskflowTaskSessionUpdate; id: number };
  "taskflow_user_settings": { row: TaskflowUserSettings; filters: TaskflowUserSettingsFilters; ordering: TaskflowUserSettingsOrdering; create: TaskflowUserSettingsCreate; update: TaskflowUserSettingsUpdate; id: number };
}

export interface UmbralOptions {
  /** Token sent as `Bearer <token>` in the `Authorization` header
      (the prefix comes from your API's declared security scheme). Override the
      prefix with `tokenPrefix` — e.g. an API that expects `Token <key>`. */
  token?: string;
  /** Overrides the `Authorization` prefix for `token`. Defaults to
      "Bearer", read from the security scheme. */
  tokenPrefix?: string;
  /** API key sent in the `X-API-Key` header (the header name comes from
      your API's declared apiKey scheme). Override with `apiKeyHeader`. */
  apiKey?: string;
  /** Overrides the header `apiKey` is sent in. Defaults to "X-API-Key",
      read from the security scheme. */
  apiKeyHeader?: string;
  /** Called whenever the live token changes — `auth.login()` sets it,
      `auth.logout()` clears it (null). Persist it here if you need it across
      reloads. The client deliberately does NOT write it to localStorage: that is
      readable by any XSS on the page, and browsers already hold an httpOnly
      session cookie. Make that trade-off knowingly. */
  onToken?: (token: string | null) => void;
  /** Dynamic auth: called per request, its headers merged in last (they win).
      Use for a rotating JWT, a refresh flow, request signing — anything the
      static options above can't express. */
  getAuthHeaders?: () => Record<string, string> | Promise<Record<string, string>>;
  /** Extra static headers merged into every request. */
  headers?: Record<string, string>;
  /** `fetch` credentials mode (cookies). Defaults to "include". */
  credentials?: RequestCredentials;
  /** Custom fetch (SSR / tests). Defaults to the global `fetch`. */
  fetch?: typeof fetch;
  /** Base path of the realtime plugin, for `.on(...)`. Defaults to "/realtime". */
  realtimePath?: string;
}

/** A live subscription started by `Umbral.on`. Call `close()` to stop it. */
export interface Subscription {
  close(): void;
}

/** Handlers for model-change events. Each receives the row your `expose(...)`
    projection carries (the id by default), so you know which row to refetch. */
export interface ModelEvents<Row> {
  created?(row: Row): void;
  updated?(row: Row): void;
  deleted?(row: Row): void;
}

/** The signed-in user, from this app's `/me` + login response schema. */
export type AuthUser = { email: string; id: number; is_staff: boolean; is_superuser: boolean; username: string; };

/** Credentials the login endpoint accepts. */
export type LoginCredentials = { password: string; username: string; };

/** What a successful login returns. The token is stored on the client automatically; browsers additionally get an httpOnly session cookie. */
export interface LoginResult {
  user: AuthUser;
  token: string;
}

/** Fields the register endpoint accepts. */
export type RegisterCredentials = { email: string; password: string; username: string; };

/** The session client — reachable as `client.auth`. */
export declare class AuthClient {
  /** The bearer token currently in use, or null. */
  readonly token: string | null;
  /** Sign in. Stores the token; later requests send it automatically. */
  login(credentials: LoginCredentials): Promise<LoginResult>;
  /** Register, then adopt the returned token. */
  register(body: RegisterCredentials): Promise<LoginResult>;
  /** Clear the server session and drop the token locally. */
  logout(): Promise<void>;
  /** The current user, or `null` when not signed in (a 401 is the
      answer to "am I logged in?", not an error). */
  me(): Promise<AuthUser | null>;
}

/** Thrown when the API returns a non-2xx response. `body` is the parsed error. */
export declare class UmbralError extends Error {
  readonly status: number;
  readonly body: unknown;
  constructor(status: number, body: unknown);
}

/** A list query. Keys and value types are specific to the model it came from. */
export declare class Query<Row, Filters, Ordering> {
  /** Field filters — the keys are exactly the (field, lookup) pairs this model accepts. */
  filter(f: Filters): this;
  /** Full-text `?search=` across the model's searchable columns. */
  search(term: string): this;
  /** `?ordering=` — pass fields; prefix `-` for descending. */
  orderBy(...fields: Ordering[]): this;

  /** Set any raw query param — the escape hatch for params the typed methods don't cover. */
  param(key: string, value: string | number | boolean): this;
  /** Sparse fieldset (`?fields=`) — fetch only these columns. */
  fields(...cols: string[]): this;
  /** Fetch the list. */
  list(): Promise<Paginated<Row>>;
}

/** A typed client for this app's REST API. */
export declare class Umbral {
  constructor(baseUrl: string, opts?: UmbralOptions);

  /** The session client: login / logout / me. */
  readonly auth: AuthClient;

  /** Start a query against a REST-exposed table. */
  from<K extends keyof UmbralResources>(
    table: K,
  ): Query<UmbralResources[K]["row"], UmbralResources[K]["filters"], UmbralResources[K]["ordering"]>;

  /** Retrieve one row by primary key. */
  get<K extends keyof UmbralResources>(
    table: K,
    id: UmbralResources[K]["id"],
  ): Promise<UmbralResources[K]["row"]>;

  /** Create a row. The body type omits server-managed fields; `noedit` fields
      are allowed here (settable on create). */
  create<K extends keyof UmbralResources>(
    table: K,
    data: UmbralResources[K]["create"],
  ): Promise<UmbralResources[K]["row"]>;

  /** Partially update a row (PATCH). The body type excludes `noedit` fields. */
  update<K extends keyof UmbralResources>(
    table: K,
    id: UmbralResources[K]["id"],
    data: UmbralResources[K]["update"],
  ): Promise<UmbralResources[K]["row"]>;

  /** Delete a row by primary key. */
  delete<K extends keyof UmbralResources>(table: K, id: UmbralResources[K]["id"]): Promise<void>;

  /** Subscribe to `created` / `updated` / `deleted` for a model, over the
      realtime plugin's shared connection (one SSE stream across all tabs). The
      model must be `expose(...)`-d to `group` on the server. */
  on<K extends keyof UmbralResources>(
    table: K,
    handlers: ModelEvents<Partial<UmbralResources[K]["row"]>>,
    opts: { group: string },
  ): Subscription;
}
